// 本文件由脚本自动生成，用于卡牌合成白名单/特殊名单。
// 生成规则：
//  - AUTO   ：拥有 DynamicVar 且 OnPlay 中数值均来自变量（或经人工复核安全）的卡牌，可直接通过变量缩放合成。
//  - SPECIAL：无变量或效果数值写死/机制复杂的卡牌，使用逐卡安全规则合成。
namespace AutoChessTactics;

public static partial class SynthesisDatabase
{
private static readonly string[] AutoMergeCards =
{
    "abrasive", "accelerant", "accuracy", "acrobatics", "adaptive_strike", "adrenaline",
    "afterimage", "alignment", "all_for_one", "anger", "anticipate", "apparition",
    "armaments", "arsenal", "assassinate", "astral_pulse", "automation", "backflip",
    "backstab", "ball_lightning", "banshees_cry", "barrage", "bash", "battle_trance",
    "beam_cell", "beat_down", "beat_into_shape", "believe_in_you", "biased_cognition", "big_bang",
    "black_hole", "blade_dance", "blade_of_ink", "blade_symphony", "blaze", "blight_strike",
    "blood_wall", "bloodletting", "bludgeon", "blur", "bolas", "bombardment",
    "bone_shards", "boost_away", "boot_sequence", "borrowed_time", "bouncing_flask", "brand",
    "break", "breakthrough", "brightest_flame", "bubble_bubble", "buffer", "bulk_up",
    "bulwark", "bundle_of_joy", "burn", "burning_pact", "burst", "bury",
    "byrd_swoop", "cacophony", "calcify", "call_of_the_void", "caltrops", "capture_spirit",
    "catastrophe", "celestial_might", "charge", "charge_battery", "child_of_the_stars", "cinder",
    "clash", "claw", "cloak_and_dagger", "cloak_of_stars", "cold_snap", "collision_course",
    "colossus", "comet", "compact", "compile_driver", "concoct", "conflagration",
    "constellation", "consuming_shadow", "convergence", "coolant", "coolheaded", "coordinate",
    "corrosive_wave", "corruption", "cosmic_indifference", "countdown", "crash_landing", "creative_ai",
    "crimson_mantle", "cruelty", "crush_under", "dagger_spray", "dagger_throw", "danse_macabre",
    "dark_shackles", "dash", "deadly_poison", "deathbringer", "deaths_door", "debilitate",
    "decay", "decisions_decisions", "defend_defect", "defend_ironclad", "defend_necrobinder", "defend_regent",
    "defend_silent", "defile", "deflect", "defragment", "defy", "delay",
    "demesne", "demon_form", "devastate", "devour_life", "disintegration", "dismantle",
    "dodge_and_roll", "dominate", "doubt", "dowsing", "drain_power", "dramatic_entrance",
    "dredge", "drum_of_battle", "dual_wield", "dying_star", "echo_form", "echoing_slash",
    "end_of_days", "energy_surge", "enfeebling_touch", "entropy", "envenom", "equilibrium",
    "eradicate", "escape_plan", "eternal_armor", "evil_eye", "expertise", "expose",
    "exterminate", "fade", "falling_star", "fan_of_knives", "fasten", "fear",
    "feed", "feeding_frenzy", "feel_no_pain", "feral", "fetch", "fiend_fire",
    "fight_me", "fight_through", "finesse", "finisher", "fisticuffs", "flak_cannon",
    "flame_barrier", "flash_of_steel", "flechettes", "flick_flack", "focused_strike", "footwork",
    "foregone_conclusion", "forgotten_ritual", "friendship", "ftl", "fuel", "gamma_blast",
    "gather_light", "genesis", "genetic_algorithm", "giant_rock", "glacier", "glasswork",
    "glimmer", "glimpse_beyond", "glitterstream", "glow", "go_for_the_eyes", "grand_finale",
    "grave_warden", "graveblast", "guiding_star", "guilty", "gunk_up", "hailstorm",
    "hand_of_greed", "hand_trick", "haze", "headbutt", "heavenly_drill", "hegemony",
    "heirloom_hammer", "helix_drill", "hemokinesis", "hidden_cache", "hidden_daggers", "high_five",
    "hologram", "hotfix", "howl_from_beyond", "huddle_up", "hyperbeam", "i_am_invincible",
    "ice_lance", "imitation_learning", "impatience", "impervious", "infection", "inferno",
    "inflame", "intercept", "invoke", "iron_wave", "iteration", "jack_of_all_trades",
    "jackpot", "juggernaut", "kingly_kick", "kingly_punch", "knife_trap", "knockdown",
    "knockout_blow", "know_thy_place", "leading_strike", "leap", "leg_sweep", "lethality",
    "lift", "lightning_rod", "loop", "luminesce", "lunar_blast", "machine_learning",
    "make_it_so", "mangle", "manifest_authority", "master_of_strategy", "maul", "melancholy",
    "metamorphosis", "meteor_shower", "meteor_strike", "midnight", "mind_rot", "minion_dive_bomb",
    "minion_sacrifice", "minion_strike", "misery", "modded", "molten_fist", "momentum_strike",
    "monarchs_gaze", "monologue", "negative_pulse", "neows_fury", "neurosurge", "neutralize",
    "neutron_aegis", "no_escape", "normality", "noxious_fumes", "null", "oblivion",
    "offering", "omnislice", "one_for_all", "one_two_punch", "orbit", "outbreak",
    "outmaneuver", "outrage", "overclock", "pacts_end", "pagestorm", "pale_blue_dot",
    "panache", "panic_button", "parry", "parse", "particle_wall", "patter",
    "peck", "phantom_blades", "photon_cut", "piercing_wail", "pillage", "pillar_of_creation",
    "pinpoint", "plot", "poisoned_stab", "pommel_strike", "pounce", "predator",
    "prep_time", "prepared", "production", "prophesize", "prowess", "pull_aggro",
    "pull_from_below", "purity", "putrefy", "pyre", "radiate", "rage",
    "rally", "rampage", "rattle", "reap", "reave", "reboot",
    "rebound", "refine_blade", "reflect", "reflex", "refract", "relax",
    "resonance", "restlessness", "ricochet", "right_hand_hand", "rip_and_tear", "rocket_punch",
    "rolling_boulder", "rupture", "salvo", "scavenge", "scourge", "scrape",
    "sculpting_strike", "seance", "second_wind", "seeker_strike", "sentry_mode", "serpent_form",
    "setup_strike", "seven_stars", "shadow_shield", "shadow_step", "shadowmeld", "shame",
    "shared_fate", "shatter", "shining_strike", "shiv", "shockwave", "shroud",
    "shrug_it_off", "sic_em", "sidestep", "signal_boost", "skewer", "skim",
    "sleight_of_flesh", "slice", "slimed", "sloth", "smokestack", "snakebite",
    "sneaky", "solar_strike", "soul", "sovereign_blade", "sow", "spectrum_shift",
    "speedster", "spinner", "spirit_of_ash", "spite", "spoils_of_battle", "squash",
    "stampede", "stardust", "stomp", "stone_armor", "storm", "strangle",
    "strike_defect", "strike_ironclad", "strike_necrobinder", "strike_regent", "strike_silent", "sucker_punch",
    "sunder", "supercritical", "suppress", "survivor", "sweeping_beam", "sword_boomerang",
    "sword_sage", "synchronize", "synthesis", "tactician", "tag_team", "tank",
    "taunt", "tear_asunder", "terraforming", "tesla_coil", "the_ball", "the_bomb",
    "the_gambit", "the_scythe", "thinking_ahead", "thrash", "thrumming_hatchet", "thunder",
    "thunderclap", "toric_toughness", "toxic", "transfigure", "tremble", "true_grit",
    "turbo", "twin_strike", "ultimate_defend", "ultimate_strike", "undeath", "unrelenting",
    "untouchable", "up_my_sleeve", "uppercut", "uproar", "veilpiercer", "vicious",
    "void", "void_form", "volley", "voltaic", "waste_away", "whirlwind",
    "whistle", "wisp", "wither", "wraith_form", "wrought_in_war"
  };

private static readonly string[] SpecialCards =
{
    "abundance", "afterlife", "aggression", "alchemize", "anointed", "apotheosis",
    "ascenders_bane", "ashen_strike", "bad_luck", "barricade", "beacon_of_hope", "beckon",
    "begone", "body_slam", "bodyguard", "bullet_time", "bully", "byrdonis_egg",
    "calamity", "calculated_gamble", "capacitor", "cascade", "chaos", "chill",
    "cleanse", "clumsy", "conqueror", "crescent_spear", "curse_of_the_bell", "dark_embrace",
    "darkness", "dazed", "death_march", "debris", "debt", "demonic_shield",
    "deprecated_card", "dirge", "discovery", "distraction", "double_energy", "dualcast",
    "eidolon", "enlightenment", "enthralled", "entrench", "expect_a_fight", "flanking",
    "flatten", "folly", "forbidden_grimoire", "frantic_escape", "furnace", "fusion",
    "gang_up", "gold_axe", "greed", "guards", "hammer_time", "hang",
    "haunt", "havoc", "hello_world", "hellraiser", "hibernate", "hidden_gem",
    "ignition", "infernal_blade", "infinite_blades", "injury", "juggling", "lantern_key",
    "largesse", "legion_of_bone", "mad_science", "malaise", "master_planner", "mayhem",
    "memento_mori", "mimic", "mind_blast", "mirage", "multi_cast", "murder",
    "necro_mastery", "nightmare", "nostalgia", "not_yet", "perfected_strike", "poke",
    "poor_sleep", "precise_cut", "primal_force", "prolong", "protector", "quadcast",
    "quasar", "rainbow", "reanimate", "reaper_form", "regret", "rend",
    "royal_gamble", "royalties", "sacrifice", "scrawl", "secret_technique", "secret_weapon",
    "seeking_edge", "severance", "snap", "soot", "soul_storm", "soulbound",
    "splash", "spoils_map", "spore_mind", "spur", "squeeze", "stack",
    "stoke", "storm_of_steel", "stratagem", "subroutine", "summon_forth", "supermassive",
    "sweeping_gaze", "tempest", "the_hunt", "the_sealed_throne", "the_smith", "times_up",
    "tools_of_the_trade", "tracking", "trash_to_treasure", "tutor", "tyranny", "underworld",
    "unleash", "unmovable", "venerate", "well_laid_plans", "white_noise", "wish",
    "wound", "writhe", "zap"
  };
}
